### ISSUE TITLE
change to mongodb or something else

### ISSUE THREAD

**Issue by wgyt** [onedotprojects/scratchCommentAuth#1]
if i can figure out mongo

**Comment by retronbv** [comment]
Mongo easy

**Comment by wgyt** [comment]
> Mongo easy

@retronbv could you help with this?

**Comment by retronbv** [comment]
What help is needed

**Comment by wgyt** [comment]
> What help is needed

I have no idea how mongo works and how to use it in node

**Comment by retronbv** [comment]
Bruh talk on discord

**Comment by thecoder876** [comment]
@wgyt wut no replit db is fine

**Comment by wgyt** [comment]
> @wgyt wut no replit db is fine

we don't use replit db dum dum

**Comment by wgyt** [comment]
done in https://github.com/onedotprojects/scratchCommentAuth/commit/8975ba77636fa29072d861fe7b68fc467b7598b6?
