### ISSUE TITLE
different login systems

### ISSUE THREAD

**Issue by wgyt** [onedotprojects/scratchCommentAuth#11]
> maybe adding different types of login methods, e.g commenting on a project, commenting on users profile, auth via cloud variables, etc.

requested by @FunctionalMetatable on [Scratch](https://scratch.mit.edu/discuss/post/5189276/)

- [ ] commenting on a project, not replying
- [ ] commenting on users profile
- [ ] studio comments https://github.com/onedotprojects/scratchCommentAuth/issues/11#issuecomment-830624529

**Comment by RedGuy12** [comment]
Maybe also a studio comments option?

**Comment by wgyt** [comment]
> Maybe also a studio comments option?

That is a good idea.

**Comment by FunctionalMetatable** [comment]
studio comments with the new api
api.scratch.mit.edu/studios/:studio/comments

**Comment by wgyt** [comment]
@FunctionalMetatable thanks for the api endpoints, are studio comments in the same format as commenting on a project?

**Comment by FunctionalMetatable** [comment]
@wgyt looks like it
