### ISSUE TITLE
add urls for apis

### ISSUE THREAD

**Issue by wgyt** [onedotprojects/scratchCommentAuth#13]
apis that I should add:
- ocular
- scratchdb

**Comment by RedGuy12** [comment]
WDYM "apis"?
________________________________
From: William Horning ***@***.***>
Sent: Saturday, May 1, 2021 7:26:28 AM
To: onedotprojects/scratchCommentAuth ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [onedotprojects/scratchCommentAuth] add urls for apis (#13)


apis that I should add:

  *   ocular
  *   scratchdb

**Comment by wgyt** [comment]
> WDYM "apis"?

ocular api (https://my-ocular.jeffalo.net/api/user/wgyt)
onestate api?

**Comment by RedGuy12** [comment]
How is that related to this?

**Comment by wgyt** [comment]
> How is that related to this?

it would add another query string to the response to the server so the server could get more data about the user

**Comment by RedGuy12** [comment]
Ohh, like returning their ocular status with their user info

**Comment by wgyt** [comment]
sort of, it just gives the server the url for the ocular api, so if they need it they can use it
